# Generated by Django 5.2.10 on 2026-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewrun_and_schema_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='evidence_span',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
