# Generated by Django 5.2.10 on 2026-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_finding_evidence_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='source',
            field=models.CharField(choices=[('rule', 'Rule'), ('llm', 'LLM'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewrun',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
