# Generated by Django 5.2.10 on 2026-02-21 22:44

from django.db import migrations, models


def migrate_completed_to_succeeded(apps, schema_editor):
    review_run = apps.get_model("review", "ReviewRun")
    review_run.objects.filter(status="completed").update(status="succeeded")


def migrate_succeeded_to_completed(apps, schema_editor):
    review_run = apps.get_model("review", "ReviewRun")
    review_run.objects.filter(status="succeeded").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('review', '0004_alter_finding_severity_alter_finding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reviewrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], default='queued', max_length=20),
        ),
        migrations.RunPython(migrate_completed_to_succeeded, migrate_succeeded_to_completed),
        migrations.AddIndex(
            model_name='reviewrun',
            index=models.Index(fields=['status', 'created_at'], name='reviewrun_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('document', 'idempotency_key'), name='uniq_reviewrun_document_idempotency_key'),
        ),
    ]
