# Generated by Django 5.2.10 on 2026-02-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_reviewrun_idempotency_key_alter_reviewrun_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('extract', 'Extract'), ('rules', 'Rules'), ('llm', 'LLM'), ('persist', 'Persist')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
