# Generated by Django 5.2.10 on 2026-02-21 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('review', '0006_reviewrun_completed_at_reviewrun_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='chunk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrun',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('preprocess', 'Preprocess'), ('extract', 'Extract'), ('rules', 'Rules'), ('llm', 'LLM'), ('persist', 'Persist')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReviewChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.CharField(max_length=255)),
                ('schema_version', models.CharField(default='v1', max_length=32)),
                ('ordinal', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_chunks', to='documents.document')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='review.reviewrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'ordinal'], name='reviewchunk_run_ordinal_idx'), models.Index(fields=['document', 'chunk_id'], name='reviewchunk_doc_chunk_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'chunk_id'), name='uniq_reviewchunk_run_chunk_id')],
            },
        ),
    ]
