# Generated by Django 5.2.10 on 2026-02-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_finding_chunk_id_alter_reviewrun_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrun',
            name='cache_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='cache_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='cache_misses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='stage_timings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reviewrun',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
