# Generated by Django 5.2.10 on 2026-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_reviewrun_cache_hits_reviewrun_cache_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
