# Generated by Django 5.2.10 on 2026-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ingestion_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('spreadsheet', 'Spreadsheet')], default='text', max_length=20),
        ),
    ]
